apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "devops-learning-platform.fullname" . }}-config
  labels:
    {{- include "devops-learning-platform.labels" . | nindent 4 }}
data:
  {{- toYaml .Values.configMap.data | nindent 2 }}
