apiVersion: v2
name: devops-learning-platform
description: A Helm chart for DevOps Cloud Learning Platform
type: application
version: 1.0.0
appVersion: "1.0.0"
keywords:
  - devops
  - learning
  - education
  - cloud
maintainers:
  - name: luniemma
    url: https://github.com/luniemma
sources:
  - https://github.com/luniemma/DevOps-cloud-learning-platform
